name: Dev to Main Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.base_ref == 'dev'

    steps:
      - run: echo "Hello World, pull request from dev to main"
