name: Feature to Dev Pull Request

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'feature')

    steps:
      - run: echo "Hello World, pull request from feature to dev"
